### ISSUE TITLE
calculate onsite level

### ISSUE THREAD

**Issue by climbak** [teamrsm/analytic-spraydown#18]

**Comment by climbage** [comment]
Does this use the pyramid to "guess" what you should be able to onsite?

**Comment by climbak** [comment]
it uses your list of ticks. I'm thinking a 3 level onsight calculation. Max onsight (probably limited to some timeframe, like the pyramid will be), average onsight (by average I mean the grade you have a 50/50 chance of onsighting) and probable onsight (something like 90% of these you'll onsight)

**Comment by SaidPar** [comment]
potential functionality for the statistics package

**Comment by SaidPar** [comment]
working on db layer apis
