### ISSUE TITLE
For new users, get the user id and persist to database

### ISSUE THREAD

**Issue by SaidPar** [teamrsm/analytic-spraydown#19]

**Comment by SaidPar** [comment]
partial implementation at db level. Pass a User object when instantiating DbSprAyPI and it will persist it to the db if the user does not exist.. We still need to gather the user information from the MP API if no user exists.

**Comment by climbak** [comment]
dependent on https://github.com/teamrsm/analytic-spraydown/issues/23

**Comment by SaidPar** [comment]
Refactored. Not the opposite case. MP API is getting data, but we're not quite yet persisting to db.

**Comment by SaidPar** [comment]
Complete and installed. The data cache now handles all aspects of querying the data api and persisting to the db.
