### ISSUE TITLE
Support Change User From the Drawer

### ISSUE THREAD

**Issue by SaidPar** [teamrsm/analytic-spraydown#50]
- [x] Cache layer
 - [x] db layer
 - [x] ui layer

Open question, do we force a new user on change user to enter both email and api key or piggy back on current users' api key?

**Comment by climbak** [comment]
I think we make them enter their own, but we provide the link they can just click on to get there.

**Comment by SaidPar** [comment]
we should display the current user in the UI somewhere as well (maybe in the drawer, and pull their mp profile - i believe we get the url when we query for the user)

**Comment by climbak** [comment]
I think this is done. @SaidPar can you confirm?
