### ISSUE TITLE
Fix last access time

### ISSUE THREAD

**Issue by climbak** [teamrsm/analytic-spraydown#66]
Currently, last access time is updating every time a user accesses database. This prevents updating if logging in more than once per cache invalidate interval. It should update only after fetching data from mountain project.

**Comment by SaidPar** [comment]
We only update the last access moment on loading ticks from mountain project.

```java
public void onTicksLoaded(List<Tick> ticks) {
        /* persist to database, then retrieve latest set. */
    m_Db.upsertTicks(ticks, m_CurrentUser.getUserId());
    m_Db.updateAccessMoment(m_CurrentUser.getUserId());
```
